POSDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posadminApp.urls')),
    path('product/', include('ProductApp.urls', namespace='ProductApp')),
    path('supplier/', include('SupplierApp.urls', namespace='SupplierApp')),
    path('purchase/', include('PurchaseApp.urls', namespace='PurchaseApp')),
    path('sell/', include('SellApp.urls', namespace='SellApp')),
    path('customers/', include('CustomersApp.urls', namespace='CustomersApp')),
    path('user/', include('UserApp.urls', namespace='UserApp')),
    path('account/', include('AccountApp.urls', namespace='AccountApp')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    

SellApp/urls.py
from django.urls import path
from .views import SellCreateView, SellListView, SellUpdateView, SellDeleteView, SellDetailsView


app_name = 'SellApp'
urlpatterns = [
    path('', SellListView.as_view(), name='sale-list'),
    path('create/', SellCreateView.as_view(), name='sale-create'),
    path('update/<slug:slug>/', SellUpdateView.as_view(), name='sale-update'),
    path('delete/<slug:slug>/', SellDeleteView.as_view(), name='sale-delete'),
    path('details/<slug:slug>/', SellDetailsView.as_view(), name='sale-details'),
    

]

UserApp/urls.py
from django.urls import path
from django.conf.urls import include
from .views import UserCreationView, UserListView, UserUpdateView

app_name = 'UserApp'
urlpatterns = [
    path('', UserListView.as_view(), name='user-list'),
    path('create/', UserCreationView.as_view(), name='user-create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),

]

UserApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls.base import reverse


# Create your models here.
class UserModel(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    email = models.EmailField()
    GENDER = {
        ('Male', 'Male'),
        ('Female', 'Female'),
    }
    gender = models.CharField(choices=GENDER, max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user')

UserApp/forms.py
from django import forms
from .models import UserModel
from django.contrib.auth.models import User


class UserAddForm(forms.ModelForm):
    class Meta:
        model = UserModel
        exclude = ('user',)


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)

UserApp/views.py
from django.db import models
from django.http import request
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.urls import reverse
from .forms import UserAddForm, UpdateUserForm
from django.views.generic import View, ListView
from django.contrib.auth.models import User




# Create your views here.
class UserCreationView(View):
    template_name = 'userApp/user_creation.html'
    
    def get(self, request):
        form=UserCreationForm
        user_add_form=UserAddForm

        return render(request, self.template_name, {'user_add_form':user_add_form, 'form':form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        user_add_form = UserAddForm(request.POST)
        if form.is_valid() and user_add_form.is_valid():
            user= form.save()
            user_info=user_add_form.save(commit=False)
            user_info.user=user
            user_info.save()

            messages.success(request, 'User created')
            return redirect('UserApp:user-list')
        return render(request, self.template_name, {'user_add_form':user_add_form, 'form':form})


class UserListView(ListView):
    model = User
    template_name = 'userApp/user_list.html'
    context_object_name = 'users'




class UserUpdateView(View):
    template_name = 'userApp/user_update.html'

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        update_form= UpdateUserForm(instance=user)
        form = UserAddForm(instance=user.user)
        return render(request, self.template_name, {'update_form':update_form, 'form':form})

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        update_form = UpdateUserForm(request.POST, instance=user) #defalt model
        form = UserAddForm(request.POST, instance=user.user) #model
        if update_form.is_valid() and form.is_valid():
            user = update_form.save()
            form_user = form.save(commit=False)
            form_user.user=user
            form_user.save()
            messages.success(request, 'user updated')
            return redirect('UserApp:user-list')
        return render(request, self.template_name, {'update_form': update_form, 'form':form })

templates/userApp/user_creation.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}


<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Add Users</h4>
                    </div>
                </div>
                <div class="card-body">

                    <form action="" method='POST'>
                        {% csrf_token %}
                        <div class="row"> 
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ user_add_form.name|as_crispy_field }}
                                </div>
                            </div>    
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ user_add_form.phone_number|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ user_add_form.email|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ user_add_form.gender|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ form.username|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ form.password1|as_crispy_field}}
                                </div>
                            </div>  
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ form.password2|as_crispy_field }}
                                </div>
                                                          -->
                        </div>                            
                        <button type="submit" class="btn btn-primary mr-2">Add Customer</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </form>


                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}

templates/userApp/user_list.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
                <div>
                    <h4 class="mb-3">User List</h4>
                    
                </div>
                <a href="{% url 'UserApp:user-create' %}" class="btn btn-primary add-list"><i class="las la-plus mr-3"></i>Add User</a>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive rounded mb-3">
            <table class="data-table table mb-0 tbl-server-info">
                <thead class="bg-white text-uppercase">
                    <tr class="ligth ligth-data">
                        <th>
                            <div class="checkbox d-inline-block">
                                <input type="checkbox" class="checkbox-input" id="checkbox1">
                                <label for="checkbox1" class="mb-0"></label>
                            </div>
                        </th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Company</th>
                        <th>Awors Points</th>
                        <th>Group</th>
                        <th>Status</th>
                        <th>Store</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody class="ligth-body">

                    {% for user in users %}
                    <tr>
                        <td>
                            <div class="checkbox d-inline-block">
                                <input type="checkbox" class="checkbox-input" id="checkbox2">
                                <label for="checkbox2" class="mb-0"></label>
                            </div>
                        </td>
                        <td>{{ user.user.name }}</td>
                        <td>{{ user.user.phone_number }}</td>
                        <td>{{ user.user.email }}</td>
                        <td>{{ user.user.gender }}</td>
                        <td>{{ user.user.phone_number }}</td>
                        <td>{{ user.username }}</td>
                        <td>
                            <div class="d-flex align-items-center list-action">
                                <a class="badge badge-info mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="View"
                                    href="#"><i class="ri-eye-line mr-0"></i></a>
                                <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"
                                    href="{% url 'UserApp:user-update' pk=user.pk %}"><i class="ri-pencil-line mr-0"></i></a>
                                <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"
                                    href="#"><i class="ri-delete-bin-line mr-0"></i></a>
                            </div>
                        </td>
                    </tr>

                    {% endfor %}

                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}

templates/userApp/user_update.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}


<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Add Users</h4>
                    </div>
                </div>
                <div class="card-body">

                    <form action="" method='POST'>
                        {% csrf_token %}
                        <div class="row"> 
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ update_form.user.name|as_crispy_field }}
                                </div>
                            </div>    
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ update_form.user.phone_number|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ update_form.user.email|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ update_form.user.gender|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ form.username|as_crispy_field }}
                                </div>
                            </div>


                        <button type="submit" class="btn btn-primary mr-2">Add Customer</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </form>


                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}