POSDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posadminApp.urls')),
    path('product/', include('ProductApp.urls', namespace='ProductApp')),
    path('supplier/', include('SupplierApp.urls', namespace='SupplierApp')),
    path('purchase/', include('PurchaseApp.urls', namespace='PurchaseApp')),
    path('sell/', include('SellApp.urls', namespace='SellApp')),
    path('customers/', include('CustomersApp.urls', namespace='CustomersApp')),
    path('user/', include('UserApp.urls', namespace='UserApp')),
    path('account/', include('AccountApp.urls', namespace='AccountApp')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    

SellApp/urls.py
from django.urls import path
from .views import SellCreateView, SellListView, SellUpdateView, SellDeleteView, SellDetailsView


app_name = 'SellApp'
urlpatterns = [
    path('', SellListView.as_view(), name='sale-list'),
    path('create/', SellCreateView.as_view(), name='sale-create'),
    path('update/<slug:slug>/', SellUpdateView.as_view(), name='sale-update'),
    path('delete/<slug:slug>/', SellDeleteView.as_view(), name='sale-delete'),
    path('details/<slug:slug>/', SellDetailsView.as_view(), name='sale-details'),
    

]

SellApp/models.py
from django.db import models
from django.db.models.fields import DateField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.text import slugify
from django.urls import reverse



# Create your models here.
class Biller(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=400)


class SellModel(models.Model):
    slug = models.SlugField(unique=True)
    sell_date = models.DateField()
    reference_no = models.CharField(max_length=50, unique=True)
    biller = models.ForeignKey(Biller, on_delete=models.SET_NULL, blank=True, null=True, related_name='biller')
    Customer = models.CharField(max_length=200)
    ORDER_TAX={
        ('No tax','No tax'),
        ('GST @5%', 'GST @5%'),
        ('VAT @10%', 'VAT @10%'),
    }
    order_tax = models.CharField(choices=ORDER_TAX, max_length=50)
    order_discount = models.IntegerField(default=0, validators= [MinValueValidator(0), MaxValueValidator(100)])
    shipping = models.DecimalField(max_digits=9, decimal_places=2, blank=True)
    attach_doc = models.FileField(upload_to='files/', blank=True)
    SALE_STATUS={
        ('Completed', 'Completed'),
        ('Pending', 'Pending')
    }
    sale_status = models.CharField(choices=SALE_STATUS, max_length=50)
    PAYMENT_STATUS={
        ('Pending', 'Pending'),
        ('Dew', 'Dew'),
        ('Payment', 'Payment'),
    }

    payment_status = models.CharField(choices=PAYMENT_STATUS, max_length=50)
    sale_note= models.TextField(blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.reference_no


    def save(self, *args, **kwargs):
        self.slug=slugify(self.reference_no)
        return super().save(*args, **kwargs)


    
    def get_update_url(self):
        return reverse('SellApp:sale-update', kwargs={'slug':self.slug})

    def get_absolute_url(self):
        return reverse("SellApp:sale-details", kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse("SellApp:sale-delete", kwargs={'slug':self.slug})

SellApp/forms.py
from django import forms
from .models import SellModel


class SellForm(forms.ModelForm):
    class Meta:
        model = SellModel
        exclude = ('slug',)

        widgets = {
            'sell_date': forms.DateInput(attrs={'type':'date'}),
            'sale_note': forms.Textarea(attrs={'rows': '3'}),
        }

SellApp/views.py
import django
from django.db import models
from django.forms import forms
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from .models import SellModel
from .forms import SellForm
from django.contrib import messages
from django.urls import reverse

# Create your views here.

class SellCreateView(CreateView):
    model = SellModel
    template_name = 'sellApp/sell_create.html'
    form_class = SellForm

    def get_success_url(self):
        messages.success(self.request, 'Sell created successfull')
        return reverse('SellApp:sale-list')



class SellListView(ListView):
    model = SellModel
    context_object_name = 'all_sell'
    template_name = 'sellApp/sell_list.html'
    form_class = SellForm


class SellUpdateView(UpdateView):
    model = SellModel
    template_name = 'sellApp/sell_update.html'
    form_class = SellForm
    def get_success_url(self):
        messages.success(self.request, 'Sell updated successfull')
        return reverse('SellApp:sale-list')


class SellDeleteView(DeleteView):
    model = SellModel
    template_name = 'sellApp/sell_delete.html'
    context_object_name = 'sales'

    def get_success_url(self):
        messages.success(self.request, 'Sell delete successfull')
        return reverse('SellApp:sale-list')


class SellDetailsView(DetailView):
    model = SellModel
    template_name = 'sellApp/sell_details.html'
    context_object_name = 'sale_details'

templates/sellApp/sell_create.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}


<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Add Sale</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action='', method='POST'>
                        {% csrf_token %}
                        <div class="row">                                  
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ form.sell_date|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.reference_no|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.biller|as_crispy_field }}
                                </div> 
                            </div>  
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.Customer|as_crispy_field }}
                                </div>
                            </div>   
                            <div class="col-md-6"> 
                                <div class="form-group">
                                    {{ form.order_tax|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.order_discount|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.shipping|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.attach_doc|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6"> 
                                <div class="form-group">
                                    {{ form.sale_status|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-6"> 
                                <div class="form-group">
                                    {{ form.payment_status|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.sale_note|as_crispy_field }}
                                </div>
                            </div> 
                        </div>                            
                        <button type="submit" class="btn btn-primary mr-2">Add Sale</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->

</div>


{% endblock contentblock %}

templates/sellApp/sell_delete.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-9">

                <div class="card">
                    <div class="card-header">
                        <h4>Delete {{ sales.Customer }}</h4>
                    </div>
                    <div class="card-body">
                        <form action="" method='POST'>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Are you sure to delete {{ sales.Customer }}?</p>
                                </div>
                            </div>
        
                            <div class="btn-group">
                                <a href="{% url 'SellApp:sale-list' %}" class="btn btn-primary">Back</a>
                                <button type='submit' class="btn btn-danger">Delete</button>
                            </div>
                            
                        </form>
                    </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock contentblock %}

templates/sellApp/sell_details.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4">
            <div class="card card-block p-card">
                <div class="">
                    <div class="profile-card rounded">
                            <h3 class="font-600 text-white text-center mb-0">{{ sale_details.reference_no }}</h3>
                            
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card card-block mb-3">
                <div class="card-header d-flex justify-content-between">
                    <div class="iq-header-title">
                        <h4 class="card-title mb-0">Suppliers Details</h4>
                    </div>
                </div>
                <div class="card-body">
                    
                    <h5>Customer: {{ sale_details.Customer }}</h5>
                    <h5>Address: {{ sale_details. }}</h5>
                    <h5>Biller: {{ sale_details.biller }}</h5>
                    <h5>Tax: {{ sale_details.order_tax }}</h5>
                    <h5>Discount: {{ sale_details.order_discount }}</h5>
                    <h5>Shipping: {{ sale_details.shipping }}</h5>
                    <h5>Document: {{ sale_details.attach_doc }}</h5>
                    <h5>Sale Status: {{ sale_details.sale_status }}</h5>
                    <h5>Payment Status: {{ sale_details.payment_status }}</h5>
                    <h5>Sale Note: {{ sale_details.payment_status }}</h5>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contentblock %}

templates/sellApp/sell_list.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
                <div>
                    <h4 class="mb-3">Sale List</h4>
                    <p class="mb-0">Sales enables you to effectively control sales KPIs and monitor them in one central<br>
                    place while helping teams to reach sales goals. </p>
                </div>
                <a href="{% url 'SellApp:sale-create' %}" class="btn btn-primary add-list"><i class="las la-plus mr-3"></i>Add Sale</a>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive rounded mb-3">
            <table class="data-table table mb-0 tbl-server-info">
                <thead class="bg-white text-uppercase">
                    <tr class="ligth ligth-data">
                        <th>
                            <div class="checkbox d-inline-block">
                                <input type="checkbox" class="checkbox-input" id="checkbox1">
                                <label for="checkbox1" class="mb-0"></label>
                            </div>
                        </th>
                        <th>Date</th>
                        <th>Customer</th>
                        <th>Sale Status</th>
                        <th>Biller</th>
                        <th>Tax</th>
                        <th>Payment Status</th>
                        <th>Sale Note</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody class="ligth-body">


                    {% for sell in all_sell %}
                    <tr>
                        <td>
                            <div class="checkbox d-inline-block">
                                <input type="checkbox" class="checkbox-input" id="checkbox2">
                                <label for="checkbox2" class="mb-0"></label>
                            </div>
                        </td>
                        <td>{{ sell.sell_date }}</td>
                        
                        <td>{{ sell.Customer }}</td>
                        <td>{{ sell.sale_status }}</td>
                        <td>{{ sell.biller }}</td>                        
                        <td>{{ sell.order_tax }}</td>                        
                        <td>{{ sell.payment_status }}</td>
                        <td>{{ sell.sale_note }}</td>
                        <td>
                            <div class="d-flex align-items-center list-action">
                                <a class="badge badge-info mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="View"
                                    href="{{ sell.get_absolute_url }}"><i class="ri-eye-line mr-0"></i></a>
                                <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"
                                    href="{{ sell.get_update_url }}"><i class="ri-pencil-line mr-0"></i></a>
                                <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"
                                    href="{{ sell.get_delete_url }}"><i class="ri-delete-bin-line mr-0"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}

templates/sellApp/sell_update.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}


<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Update Sale</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action='', method='POST'>
                        {% csrf_token %}
                        <div class="row">                                  
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ form.sell_date|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.reference_no|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.biller|as_crispy_field }}
                                </div> 
                            </div>  
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.Customer|as_crispy_field }}
                                </div>
                            </div>   
                            <div class="col-md-6"> 
                                <div class="form-group">
                                    {{ form.order_tax|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.order_discount|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.shipping|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.attach_doc|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6"> 
                                <div class="form-group">
                                    {{ form.sale_status|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-6"> 
                                <div class="form-group">
                                    {{ form.payment_status|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.sale_note|as_crispy_field }}
                                </div>
                            </div> 
                        </div>                            
                        <button type="submit" class="btn btn-primary mr-2">Update Sale</button>
                        <a class="btn btn-danger" href="{% url 'SellApp:sale-list' %}">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->

</div>


{% endblock contentblock %}