POSDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posadminApp.urls')),
    path('product/', include('ProductApp.urls', namespace='ProductApp')),
    path('supplier/', include('SupplierApp.urls', namespace='SupplierApp')),
    path('purchase/', include('PurchaseApp.urls', namespace='PurchaseApp')),
    path('sell/', include('SellApp.urls', namespace='SellApp')),
    path('customers/', include('CustomersApp.urls', namespace='CustomersApp')),
    path('user/', include('UserApp.urls', namespace='UserApp')),
    path('account/', include('AccountApp.urls', namespace='AccountApp')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    

ProductApp/urls.py
from django.urls import path
from django.conf.urls import include
from ProductApp.views import CategoryCreateView, CategoryList, CategoryUpdate, CategoryDetail, CategoryDelete, ProductCreateView, ProductListView, ProductUpdateView, ProductDeleteView, ProductDetailView


app_name = 'ProductApp'
urlpatterns = [
    #path('category/', CategoryCreateView.as_view(), name='category'),
    path('category/', CategoryList.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/update/<slug:slug>/', CategoryUpdate.as_view(), name='category-update'),
    path('category/detail/<slug:slug>/', CategoryDetail.as_view(), name='category-detail'),
    path('category/delete/<slug:slug>/', CategoryDelete.as_view(), name='category-delete'),
    path('product/create/', ProductCreateView.as_view(), name='product-create'),
    path('product/list/', ProductListView.as_view(), name='product-list'),
    path('product/update/<slug:slug>/', ProductUpdateView.as_view(), name='product-update'),
    path('product/delete/<slug:slug>/', ProductDeleteView.as_view(), name='product-delete'),
    path('product/detail/<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    
]

SellApp/urls.py
from django.urls import path
from .views import SellCreateView, SellListView, SellUpdateView, SellDeleteView, SellDetailsView


app_name = 'SellApp'
urlpatterns = [
    path('', SellListView.as_view(), name='sale-list'),
    path('create/', SellCreateView.as_view(), name='sale-create'),
    path('update/<slug:slug>/', SellUpdateView.as_view(), name='sale-update'),
    path('delete/<slug:slug>/', SellDeleteView.as_view(), name='sale-delete'),
    path('details/<slug:slug>/', SellDetailsView.as_view(), name='sale-details'),
    

]

posadminApp/urls.py
from django.urls import path
from django.conf.urls import include
from posadminApp.views import HomeView


app_name = 'posadminApp'
urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

ProductApp/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify



# Create your models here.
class Category(models.Model):
    cate_image= models.ImageField(verbose_name='Category Image', upload_to='products/', blank=True)
    cate_name=models.CharField(verbose_name='Category name', max_length=100, unique=True)
    cate_shot_des = models.CharField(verbose_name='Category short description', max_length=200, blank=True)
    cate_des = models.TextField(verbose_name='Category description', blank=True)
    parent = models.ForeignKey('self', verbose_name='Parent Category',  on_delete=models.SET_NULL, blank=True, null=True, related_name='product_related')
    slug = models.SlugField(unique=True)
    code = models.CharField(verbose_name='Category code', max_length=50)
    is_active = models.BooleanField(verbose_name='Is Active', default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.cate_name
        
    def image_url(self):
        try:
            url=self.cate_image.url
        except:
            url=''
        return url


    def save(self, *args, **kwargs):
        self.slug = slugify(self.cate_name)
        return super().save(*args, **kwargs)

    def get_update_url(self):
        return reverse("ProductApp:category-update", kwargs={'slug':self.slug})

    def get_absolute_url(self):
        return reverse("ProductApp:category-detail", kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse("ProductApp:category-delete", kwargs={'slug':self.slug})
    


class Product(models.Model):
    Product_Type=(
        ('standart', 'standard'),
        ('conbo', 'combo'),
        ('digital', 'digital'),
    )
    product_type= models.CharField(choices=Product_Type, max_length=50, default='standard')
    tax=(
        ('Exclude', 'Exclude'),
        ('Include', 'Include'),
        ('None', 'None'),
        
    )
    name = models.CharField(max_length=60, unique=True)
    code = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cost = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    tax_mathod = models.CharField(choices=tax, max_length=50, default='None')
    quantity = models.PositiveIntegerField(default=0)
    description = models.TextField(blank=True)
    product_image= models.ImageField(verbose_name='Product Image', upload_to='products/', blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def image_url(self):
        try:
            url=self.product_image.url
        except:
            url=''
        return url

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    
    def get_update_url(self):
        return reverse("ProductApp:product-update", kwargs={'slug':self.slug})

    def get_absolute_url(self):
        return reverse("ProductApp:product-detail", kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse("ProductApp:product-delete", kwargs={'slug':self.slug})

ProductApp/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Category, Product


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'
        
        
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('slug',)
        

ProductApp/views.py
from django.db import models
from django.db.models import fields
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from .models import Category, Product
from .forms import CategoryForm, ProductForm
from django.urls import reverse
from django.contrib import messages

# Create your views here.

#category
class CategoryCreateView(CreateView):
    model = Category
    fields = ('cate_name', 'parent', 'cate_image', 'code', 'is_active')
    template_name = "productApp/prod_add_category.html"
    form_classes = CategoryForm

    def get_success_url(self):
        messages.success(self.request, 'Your category added ')
        return reverse('posadminApp:home')


class CategoryList(ListView):
    model=Category
    context_object_name = 'Categories'
    template_name= 'productApp/product_category_list.html'


class CategoryUpdate(UpdateView):

    model = Category
    fields = ('cate_name', 'parent', 'cate_image', 'code', 'is_active')
    template_name= 'productApp/product_category_update.html'
    def get_success_url(self):
        messages.success(self.request, 'Your category updated ')
        return reverse('ProductApp:category-list')


class CategoryDelete(DeleteView):
    model = Category
    template_name= 'productApp/product_category_delete.html'
    context_object_name = 'category'
    def get_success_url(self):
        messages.success(self.request, 'Your category Deleted ')
        return reverse('ProductApp:category-list')


class CategoryDetail(DetailView):
    model = Category
    template_name= 'productApp/product_category_detail.html'
    context_object_name = 'category_details'


#product
class ProductCreateView(CreateView):
    model = Product
    fields = ('product_type', 'name', 'code', 'price', 'product_category', 'cost', 'tax_mathod', 'quantity', 'description', 'product_image')

    template_name = "productApp/product_add.html"
    form_classes = ProductForm

    def get_success_url(self):
        messages.success(self.request, 'Your product{0} added'.format(self.object))
        return reverse('ProductApp:product-list')


class ProductListView(ListView):
    model = Product
    fields = ('product_type', 'name', 'code', 'price', 'product_category', 'cost', 'tax_mathod', 'quantity', 'description', 'product_image')
    context_object_name = 'products'
    template_name = "productApp/product_list.html"



class ProductUpdateView(UpdateView):
    model = Product
    fields = ('product_type', 'name', 'code', 'price', 'product_category', 'cost', 'tax_mathod', 'quantity', 'description', 'product_image')

    template_name = "productApp/product_update.html"
    form_classes = ProductForm

    def get_success_url(self):
        messages.success(self.request, 'Your product updated ')
        return reverse('ProductApp:product-list')


class ProductDeleteView(DeleteView):
    model = Product
    template_name= 'productApp/product_delete.html'
    context_object_name = 'product'
    def get_success_url(self):
        messages.success(self.request, 'Your product Deleted ')
        return reverse('ProductApp:product-list')


class ProductDetailView(DetailView):
    model = Product
    template_name= 'productApp/product_detail.html'
    context_object_name = 'product_details'

templates/productApp/prod_add_category.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}


    <div class="container-fluid add-form-list">
        <div class="row justify-content-center">
            <div class="col-sm-10">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">Add category</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="" method='POST' enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row"> 

                                <div class="col-md-12">
                                    <div class="form-group">
                                        {{ form.cate_image|as_crispy_field }}
                                        
                                    </div>
                                </div>

                                <div class="col-md-12 ">                      
                                    <div class="form-group">
                                        {{ form.cate_name|as_crispy_field }}
                                    </div>
                                </div>  

                                <div class="col-md-12 ">                      
                                    <div class="form-group">
                                        {{ form.code|as_crispy_field }}
                                    </div>
                                </div>  


                                <div class="col-md-12">
                                    <div class="form-group">
                                        {{ form.parent|as_crispy_field }}
                                    </div>
                                </div>  

                                <div class="col-md-12">
                                    <div class="form-group">
                                        {{ form.is_active|as_crispy_field }}
                                    </div>
                                </div>                                 
                            </div>       

                            <button type="submit" class="btn btn-primary mr-2">Add category</button>                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <!-- Page end  -->
    </div>

{% endblock contentblock %}

templates/productApp/product_add.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}

<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between bg-primary">
                    <div class="header-title">
                        <h4 class="card-title">Add Product</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method='POST' enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.product_type|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.code|as_crispy_field }}
                                </div>
                            </div>
                            <!-- <div class="col-md-6">

                                <div class="form-group">
                                    <label>Barcode Symbology *</label>
                                    <select name="type" class="selectpicker form-control" data-style="py-0">
                                        <option>CREM01</option>
                                        <option>UM01</option>
                                        <option>SEM01</option>
                                        <option>COF01</option>
                                        <option>FUN01</option>
                                        <option>DIS01</option>
                                        <option>NIS01</option>
                                    </select>
                                </div>
                            </div> -->

                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.product_category|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.cost|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.quantity|as_crispy_field }}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.price|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.tax_mathod|as_crispy_field }}
                                </div>
                            </div>
                            
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.product_image|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.description|as_crispy_field }}                                    
                                    
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Add Product</button>
                        <a href="{% url 'posadminApp:home' %}" class="btn btn-danger">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}

templates/productApp/product_category_delete.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-9">

        <div class="card">
            <div class="card-header">
                <h4>Delete {{category.cate_name}}</h4>
            </div>
            <div class="card-body">
                <form action="" method='POST'>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <p>Are you sure to delete {{category.cate_name}} category?</p>
                        </div>
                    </div>

                    <div class="btn-group">
                        <a href="{% url 'ProductApp:category-list' %}" class="btn btn-primary">Back</a>
                        <button type='submit' class="btn btn-danger">Delete</button>
                    </div>
                    
                </form>
            </div>
            </div>

        </div>
    </div>
</div>
{% endblock contentblock %}

templates/productApp/product_category_list.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}




<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
                <div>
                    <h4 class="mb-3">Category List( {{ Categories.count }} )</h4>
                    
                </div>
                <a href="{% url 'ProductApp:category-create' %}" class="btn btn-primary add-list"><i class="las la-plus mr-3"></i>Add
                    Category</a>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive rounded mb-3">
                <table class="data-table table mb-0 tbl-server-info">
                    <thead class="bg-white text-uppercase">
                        <tr class="ligth ligth-data">
                            <th>
                                <div class="checkbox d-inline-block">
                                    <input type="checkbox" class="checkbox-input" id="checkbox1">
                                    <label for="checkbox1" class="mb-0"></label>
                                </div>
                            </th>
                            <th>Image</th>
                            <th>Code</th>
                            <th>Category</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="ligth-body">
                        

                        {% for category in Categories %}
                        <tr>
                            <td>
                                <div class="checkbox d-inline-block">
                                    <input type="checkbox" class="checkbox-input" id="checkbox2">
                                    <label for="checkbox2" class="mb-0"></label>
                                </div>
                            </td>


                            <td>
                                <div class="d-flex align-items-center">
                                    <img src="{{ category.image_url }}"
                                        class="img-fluid rounded avatar-50 mr-3" alt="image">
                                    <div>
                                        {{ category.cate_name }}
                                        <p class="mb-0"><small>{{ category.cate_shot_des }}</small></p>
                                    </div>
                                </div>
                            </td>
                            <td>{{ category.code }}</td>
                            <td>
                                {% if category.parent %}
                                {{ category.parent }}
                                {% else %}
                                <p>no category</p>
                                {% endif %}
                            </td>

                            <td>
                                <div class="d-flex align-items-center list-action">
                                    <a class="badge badge-info mr-2" data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="View" href="{{ category.get_absolute_url }}"><i class="ri-eye-line mr-0"></i></a>
                                    <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="Edit" href="{{ category.get_update_url }}"><i class="ri-pencil-line mr-0"></i></a>
                                    <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="Delete" href="{{ category.get_delete_url }}"><i
                                            class="ri-delete-bin-line mr-0"></i></a>
                                </div>
                            </td>

                        </tr>
                        {% endfor %}


                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>
<!-- Modal Edit -->
<div class="modal fade" id="edit-note" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="popup text-left">
                    <div class="media align-items-top justify-content-between">
                        <h3 class="mb-3">Product</h3>
                        <div class="btn-cancel p-0" data-dismiss="modal"><i class="las la-times"></i></div>
                    </div>
                    <div class="content edit-notes">
                        <div class="card card-transparent card-block card-stretch event-note mb-0">
                            <div class="card-body px-0 bukmark">
                                <div class="d-flex align-items-center justify-content-between pb-2 mb-3 border-bottom">
                                    <div class="quill-tool">
                                    </div>
                                </div>
                                <div id="quill-toolbar1">
                                    <p>Virtual Digital Marketing Course every week on Monday, Wednesday and
                                        Saturday.Virtual Digital Marketing Course every week on Monday</p>
                                </div>
                            </div>
                            <div class="card-footer border-0">
                                <div class="d-flex flex-wrap align-items-ceter justify-content-end">
                                    <div class="btn btn-primary mr-3" data-dismiss="modal">Cancel</div>
                                    <div class="btn btn-outline-primary" data-dismiss="modal">Save</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contentblock %}

templates/productApp/product_list.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="d-flex flex-wrap flex-wrap align-items-center justify-content-between mb-4">

                    <a href="{% url 'ProductApp:product-create' %}" class="btn btn-primary add-list"><i
                            class="las la-plus mr-3"></i>Add Product</a>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="table-responsive rounded mb-3">
                    <table class="data-tables table mb-0 tbl-server-info">
                        <thead class="bg-white text-uppercase">
                            <tr class="ligth ligth-data">
                                <th>
                                    <div class="checkbox d-inline-block">
                                        <input type="checkbox" class="checkbox-input" id="checkbox1">
                                        <label for="checkbox1" class="mb-0"></label>
                                    </div>
                                </th>
                                <th>Product</th>
                                <th>Code</th>
                                <th>Category</th>
                                <th>Price</th>
                                <th>Brand Name</th>
                                <th>Cost</th>
                                <th>Quantity</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody class="ligth-body">
                            {% for product in products %}
                            <tr>
                                
                                    <td>
                                        <div class="checkbox d-inline-block">
                                            <input type="checkbox" class="checkbox-input" id="checkbox2">
                                            <label for="checkbox2" class="mb-0"></label>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <img src="{{ product.image_url }}"
                                                class="img-fluid rounded avatar-50 mr-3" alt="image">
                                            <div>
                                                {{ product.name }}
                                            </div>
                                        </div>
                                    </td>
                                    <td>{{ product.code }}</td>
                                    <td>{{ product.product_category }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.product_type }}</td>
                                    <td>{{ product.cost }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>
                                        <div class="d-flex align-items-center list-action">
                                            <a class="badge badge-info mr-2" data-toggle="tooltip"
                                                data-placement="top" title="" data-original-title="View" href="{{ product.get_absolute_url }}"><i
                                                    class="ri-eye-line mr-0"></i></a>

                                            <a class="badge bg-success mr-2" data-toggle="tooltip"
                                                data-placement="top" title="" data-original-title="Edit" href="{{ product.get_update_url }}"><i
                                                    class="ri-pencil-line mr-0"></i></a>
                                                    
                                            <a class="badge bg-warning mr-2" data-toggle="tooltip"
                                                data-placement="top" title="" data-original-title="Delete"
                                                href="{{ product.get_delete_url }}"><i class="ri-delete-bin-line mr-0"></i></a>
                                        </div>
                                    </td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Page end  -->
    </div>
    <!-- Modal Edit -->
    <div class="modal fade" id="edit-note" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="popup text-left">
                        <div class="media align-items-top justify-content-between">
                            <h3 class="mb-3">Product</h3>
                            <div class="btn-cancel p-0" data-dismiss="modal"><i class="las la-times"></i></div>
                        </div>
                        <div class="content edit-notes">
                            <div class="card card-transparent card-block card-stretch event-note mb-0">
                                <div class="card-body px-0 bukmark">
                                    <div
                                        class="d-flex align-items-center justify-content-between pb-2 mb-3 border-bottom">
                                        <div class="quill-tool">
                                        </div>
                                    </div>
                                    <div id="quill-toolbar1">
                                        <p>Virtual Digital Marketing Course every week on Monday, Wednesday and
                                            Saturday.Virtual Digital Marketing Course every week on Monday</p>
                                    </div>
                                </div>
                                <div class="card-footer border-0">
                                    <div class="d-flex flex-wrap align-items-ceter justify-content-end">
                                        <div class="btn btn-primary mr-3" data-dismiss="modal">Cancel</div>
                                        <div class="btn btn-outline-primary" data-dismiss="modal">Save</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock contentblock %}