AccountApp/urls.py
from django.urls import path
from django.conf.urls import include
from .views import AccountCreateView, AccountListView, AccountUpdateView

app_name = 'AccountApp'
urlpatterns = [
    path('', AccountListView.as_view(), name='account-list'),
    path('create/', AccountCreateView.as_view(), name='account-create'),
    path('update/<int:pk>/', AccountUpdateView.as_view(), name='account-update'),


]

POSDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posadminApp.urls')),
    path('product/', include('ProductApp.urls', namespace='ProductApp')),
    path('supplier/', include('SupplierApp.urls', namespace='SupplierApp')),
    path('purchase/', include('PurchaseApp.urls', namespace='PurchaseApp')),
    path('sell/', include('SellApp.urls', namespace='SellApp')),
    path('customers/', include('CustomersApp.urls', namespace='CustomersApp')),
    path('user/', include('UserApp.urls', namespace='UserApp')),
    path('account/', include('AccountApp.urls', namespace='AccountApp')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    

SellApp/urls.py
from django.urls import path
from .views import SellCreateView, SellListView, SellUpdateView, SellDeleteView, SellDetailsView


app_name = 'SellApp'
urlpatterns = [
    path('', SellListView.as_view(), name='sale-list'),
    path('create/', SellCreateView.as_view(), name='sale-create'),
    path('update/<slug:slug>/', SellUpdateView.as_view(), name='sale-update'),
    path('delete/<slug:slug>/', SellDeleteView.as_view(), name='sale-delete'),
    path('details/<slug:slug>/', SellDetailsView.as_view(), name='sale-details'),
    

]

AccountApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class AccountModel(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    email = models.EmailField()
    GENDER = {
        ('Male', 'Male'),
        ('Female', 'Female'),
    }
    gender = models.CharField(choices=GENDER, max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='related_user')

    
    def __str__(self):
        return self.name

    

AccountApp/forms.py
from django import forms
from django.forms import fields
from .models import AccountModel
from django.contrib.auth.models import User


class AccountInfoForm(forms.ModelForm):
    class Meta:
        model = AccountModel
        exclude = ('user',)


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)
        

AccountApp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404, redirect, render

from UserApp.forms import UpdateUserForm
from .models import AccountModel
from .forms import AccountInfoForm, AccountUpdateForm
from django.views.generic import View, ListView
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth.models import User

# Create your views here.
class AccountCreateView(View):
    template_name = 'accountApp/acc_create.html'

    def get(self, request):
        acc_crt_form = UserCreationForm #username, pass1, pass2
        acc_info_form = AccountInfoForm
        return render(request, self.template_name,{'acc_crt_form':acc_crt_form, 'acc_info_form':acc_info_form})


    def post(self, request):
        acc_crt_form = UserCreationForm(request.POST) #username, pass1, pass2
        acc_info_form = AccountInfoForm(request.POST) #user info
        if acc_crt_form.is_valid() and acc_info_form.is_valid():
            #save user acc
            user_create = acc_crt_form.save()
            #save user acc info
            user_info= acc_info_form.save(commit=False)
            #set user_create in user_info with (user) OneToOneField of AccountModel
            user_info.user = user_create
            user_info.save()

            messages.success(request, 'Account created successfull')
            return redirect('AccountApp:account-list')
        return render(request, self.template_name, {'acc_crt_form':acc_crt_form, 'acc_info_form':acc_info_form})


class AccountUpdateView(View):
    template_name = 'accountApp/acc_update.html'

    def get(self, request, pk):
        #user select by pk
        user = get_object_or_404(User, pk=pk)
        update_form = AccountUpdateForm(instance=user)
        acc_info = AccountInfoForm(instance=user.related_user)
        return render(request, self.template_name, {'acc_info':acc_info, 'update_form':update_form})


    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        #defalt model user info instance
        update_form = AccountUpdateForm(request.POST, instance=user) 
        acc_info = AccountInfoForm(request.POST, instance=user.related_user)
        if update_form.is_valid():
            user_update=update_form.save()
            acc_info_save = acc_info.save(commit=False)
            acc_info_save.user = user_update
            acc_info_save.save()
            messages.success(request, 'Account updated')
            return redirect('AccountApp:account-list')
        return render(request, self.template_name, {'update_form':update_form, 'acc_info':acc_info})


class AccountListView(ListView):
    model = User
    template_name = 'accountApp/account_list.html'
    context_object_name = 'accounts'
    queryset = User.objects.filter(is_superuser=False).prefetch_related('related_user')


def logout_view(request):
    logout(request)

templates/accountApp/acc_create.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}

<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Create Account</h4>
                    </div>
                </div>
                <div class="card-body">

                    <form action="" method='POST'>
                        {% csrf_token %}
                        <div class="row"> 
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ acc_info_form.name|as_crispy_field }}
                                </div>
                            </div>    
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ acc_info_form.phone_number|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ acc_info_form.email|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ acc_info_form.gender|as_crispy_field }}
                                </div>
                            </div> 
                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ acc_crt_form.username|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ acc_crt_form.password1|as_crispy_field}}
                                </div>
                            </div>  

                            <div class="col-md-6">                      
                                <div class="form-group">
                                    {{ acc_crt_form.password2|as_crispy_field }}
                                </div>

                        </div>                            
                        <button type="submit" class="btn btn-primary mr-2">Create Account</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}

templates/accountApp/acc_update.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}
{% load crispy_forms_tags %}

<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Update Account</h4>
                    </div>
                </div>
                <div class="card-body">

                    <form action="" method='POST'>
                        {% csrf_token %}
                        <div class="row"> 
                            
                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ acc_info.name|as_crispy_field }}
                                </div>
                            </div>

                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ acc_info.phone_number|as_crispy_field }}
                                </div>
                            </div>

                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ acc_info.email|as_crispy_field }}
                                </div>
                            </div>

                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ acc_info.gender|as_crispy_field }}
                                </div>
                            </div>

                            <div class="col-md-12">                      
                                <div class="form-group">
                                    {{ update_form.username|as_crispy_field }}
                                </div>
                            </div>

                        <button type="submit" class="btn btn-primary mr-2">Update Account</button>
                        <a class="btn btn-danger" href="{% url 'AccountApp:account-list' %}">Cancel</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}

templates/accountApp/account_list.html
{% extends "base.html" %}
{% load static %}
{% block contentblock %}


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
                <div>
                    <h4 class="mb-3">Account List</h4>
                    
                </div>
                <a href="{% url 'AccountApp:account-create' %}" class="btn btn-primary add-list"><i class="las la-plus mr-3"></i>Add User</a>
            </div>
        </div>


        <div class="col-lg-12">
            <div class="table-responsive rounded mb-3">
            <table class="data-table table mb-0 tbl-server-info">
                <thead class="bg-white text-uppercase">
                    <tr class="ligth ligth-data">
                        <th>
                            <div class="checkbox d-inline-block">
                                <input type="checkbox" class="checkbox-input" id="checkbox1">
                                <label for="checkbox1" class="mb-0"></label>
                            </div>
                        </th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Gender</th>
                        <th>Phone No</th>
                        <th>Username</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody class="ligth-body">

                    {% for account in accounts %}
                    <tr>
                        <td>
                            <div class="checkbox d-inline-block">
                                <input type="checkbox" class="checkbox-input" id="checkbox2">
                                <label for="checkbox2" class="mb-0"></label>
                            </div>
                        </td>
                        <td>{{ account.related_user.name }}</td>
                        <td>{{ account.related_user.email }}</td>
                        <td>{{ account.related_user.gender }}</td>
                        <td>{{ account.related_user.phone_number }}</td>
                        <td>{{ account.username }}</td>
                        <td>

                            <div class="d-flex align-items-center list-action">
                                <a class="badge badge-info mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="View"
                                    href="#"><i class="ri-eye-line mr-0"></i></a>
                                <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"
                                    href="{% url 'AccountApp:account-update' pk=account.pk %}"><i class="ri-pencil-line mr-0"></i></a>
                                <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"
                                    href="#"><i class="ri-delete-bin-line mr-0"></i></a>
                            </div>
                        </td>
                    </tr>


                    {% endfor %}

                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock contentblock %}